[traces-limits]

ADD                 = 524286
BIN                 = 262128
BIN_RT              = 262144
EC_DATA             = 4084
EXT                 = 131060
HUB                 = 2097150
INSTRUCTION_DECODER = 512
MMIO                = 1048576
MMU                 = 524288
MMU_ID              = 256
MOD                 = 131064
MUL                 = 65527
MXP                 = 524284
PHONEY_RLP          = 65536
PUB_HASH            = 32768
PUB_HASH_INFO       = 8192
PUB_LOG             = 16384
PUB_LOG_INFO        = 16384
RLP                 = 504
ROM                 = 4194302
SHF                 = 65520
SHF_RT              = 4096
TX_RLP              = 110000
WCP                 = 262128

BLOCK_TX       = 200
BLOCK_L2L1LOGS = 16
BLOCK_KECCAK   = 8192


PRECOMPILE_ECRECOVER = 100
PRECOMPILE_SHA2      = 100
PRECOMPILE_RIPEMD    = 100
PRECOMPILE_IDENTITY  = 10000
PRECOMPILE_MODEXP    = 1000
PRECOMPILE_ECADD     = 1000
PRECOMPILE_ECMUL     = 100
PRECOMPILE_ECPAIRING = 100
PRECOMPILE_BLAKE2F   = 512
